name: TFM_environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - gdal
  - fiona
  - geopandas
  - scikit-learn
  - matplotlib
  - numpy=
  - seaborn=
  - pydotplus
  - jupyter
  - umap-learn
  - scipy
  - openpyxl
  - rasterio
  - cdsapi
  - xarray
  - raster2xyz